### ISSUE TITLE
应该用 CocoaPods 生成的 IGuide.xcworkspace 文件来打开demo

### ISSUE THREAD

**Issue by SiterZzz** [whatsbug/IGuide#1]

**Comment by whatsbug** [comment]
请问具体是什么错？我这边尝试是没有任何问题的

**Comment by whatsbug** [comment]
同学，你应该用 `CocoaPods` 生成的 `IGuide.xcworkspace` 文件来打开项目，而不是用 `IGuide.xcodeproj` 文件

**Comment by whatsbug** [comment]
同学，这个issue我先关了，如果你那边确实有问题，麻烦你提供错误信息然后再开启哈
